steps:
  # Step : 0 : Run the generate script to create static JSON files using the Bun image
  - name: 'oven/bun:alpine'
    entrypoint: 'bun'
    args: ['run', 'generate.ts', '--crawl']
    id: 'generate'

  # Step : 1 : Build the Docker image using the standard Node.js image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/astro-app:$SHORT_SHA', '.']
    id: 'build-image'
    waitFor: ['generate']

  # Step : 2 : Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/astro-app:$SHORT_SHA']
    id: 'push-image'
    waitFor: ['build-image']

  # Step : 3 : Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'iam-roles-permissions'
      - '--image'
      - 'gcr.io/$PROJECT_ID/astro-app:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--cpu'
      - '1'
      - '--memory'
      - '1024Mi'
    waitFor: ['push-image']

images:
  - 'gcr.io/$PROJECT_ID/astro-app:$SHORT_SHA'