steps:
  # Run the generate script to create static JSON files using the Bun image
  - name: 'Run Generate Script'
    image: 'oven/bun:alpine'
    workingDirectory: '/workspace'
    entrypoint: 'bun'
    args: ['run', 'generate.ts', '--crawl']

  # Build the Docker image using the standard Node.js image
  - name: 'Build Docker Image'
    image: 'gcr.io/cloud-builders/docker'
    workingDirectory: '/workspace'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/astro-app:$SHORT_SHA', '.']

  # Push the Docker image to Google Container Registry
  - name: 'Push Docker Image'
    image: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/astro-app:$SHORT_SHA']

  # Deploy the Docker image to Cloud Run
  - name: 'Deploy to Cloud Run'
    image: 'gcr.io/google-cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'iam-roles-permissions'
      - '--image'
      - 'gcr.io/$PROJECT_ID/astro-app:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--cpu'
      - '1'
      - '--memory'
      - '1024Mi'

images:
  - 'gcr.io/$PROJECT_ID/astro-app:$SHORT_SHA'