# .github/workflows/generate-and-commit-roles.yml
name: "Daily IAM Roles Update"

on:
  schedule:
    - cron: "0 12 * * 0" # 2 AM UTC every Sunday
  workflow_dispatch:

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  REGION: "${{ secrets.REGION }}"

jobs:
  generate_roles:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write" # Needs write permission to commit
      id-token: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup Node"
        uses: "actions/setup-node@v4"

      - name: "Install dependencies"
        run: "npm install"

      - id: "sdk-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          token_format: "access_token"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: "Run generate script to get latest IAM roles"
        run: "npm run generate"

      - name: "Commit updated roles"
        uses: "stefanzweifel/git-auto-commit-action@v5"
        with:
          commit_message: "chore: Auto-update IAM roles from daily cron"
          branch: "${{ github.ref_name }}" # Commits to the current branch
          file_pattern: "src/content/roles/**/*.json"
