# .github/workflows/generate-and-commit-roles.yml
name: "Daily IAM Roles Update"

on:
  schedule:
    - cron: "0 12 * * 0" # 2 AM UTC every Sunday
  workflow_dispatch:

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  REGION: "${{ secrets.REGION }}"

jobs:
  generate_roles:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write" # Needs write permission to commit
      id-token: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup Node"
        uses: "actions/setup-node@v4"
        with:
          node-version: "20"
          cache: "npm"

      - name: "Install dependencies"
        run: "npm install"

      - id: "sdk-auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          token_format: "access_token"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: "Run generate script to get latest IAM roles"
        run: "npm run generate"

      - name: "Verify file Changes"
        id: "check_changes"
        run: |
          git status
          echo "---- Verifying changes ----"
          ls -R src/content/roles || echo "Directory src/content/roles not found"

      - name: "Commit updated roles"
        uses: "stefanzweifel/git-auto-commit-action@v5"
        with:
          commit_message: "chore: Auto-update IAM roles from daily cron"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
